mupic_config_file : include_stmt? stmts

stmts : statement*

?statement : default_stmt 
    | output_stmt | cover_stmt
    | image_stmt  | text_stmt

include_stmt : "include" ESCAPED_STRING

default_stmt : "default" DEFLT_PROP ESCAPED_STRING
DEFLT_PROP : "font" | "fill"

output_stmt : "output" "{" output_setting+ "}"
?output_setting : path_option
    | size_2d_option
    | color_option
    | "background" "=" ESCAPED_STRING -> background_option
    | margin_int_option
    | border_spec

cover_stmt : "cover" "{" cover_setting+ "}"
?cover_setting : path_option
    | "fit" "=" WORD -> fit_option // check the actual string in the Transformer
    | "crop" "=" WORD -> crop_option
    | "align" "=" WORD -> align_option
    | margin_int_option
    | border_spec

image_stmt : "image" ESCAPED_STRING? "{" image_setting+ "}"
?image_setting : path_option
    | size_2d_option
    | "mask" "=" WORD -> mask_option
    | position_option
    | border_spec
    | margin_int_option
    | color_option
    | path_option

text_stmt : "text" ESCAPED_STRING? "{" text_setting+ "}"
?text_setting : "text" "=" ESCAPED_STRING -> text_option
    | "size" "=" INTEGER -> size_int_option
    | position_option
    | "rotation" "=" INTEGER -> rotation_option
    | "fill" "=" ESCAPED_STRING -> fill_option // This is a color
    | "font" "=" ESCAPED_STRING -> font_option
    | stroke_spec

border_spec : "border" "{" border_setting+ "}"
// Changing this to directly use color_option rule
// causes a reduce/reduce conflict with stroke_setting
?border_setting : /color/ "=" ESCAPED_STRING -> color_option
    | width_spec

stroke_spec : "stroke" "{" stroke_setting+ "}"
?stroke_setting : color_option
    | "width" "=" INTEGER -> width_option

width_spec : "width" "=" INTEGER
    | "width" "{" INTEGER "}"
    | "width" "{" one_side+ "}"
one_side : /[ltrb]/ "=" INTEGER

path_option : "path" "=" ESCAPED_STRING
margin_int_option : "margin" "=" INTEGER
size_2d_option : "size" "=" SIZE
position_option : "position" "=" ESCAPED_STRING
color_option : "color" "=" ESCAPED_STRING

SIZE : /\d+(x\d+)?/
INTEGER : /[-+]?\d+/
// BARE_STRING : /[^ \t,\n"']+/
%import common.ESCAPED_STRING
%import common.SH_COMMENT
%import common.WS
%import common.WORD
%ignore SH_COMMENT
%ignore WS
