config : include_stmt? stmts

stmts : statement*

statement : default_stmt 
    | output_stmt | cover_stmt
    | image_stmt  | text_stmt

include_stmt : "include" path
path : ESCAPED_STRING

default_stmt : "default" DEFLT_PROP ESCAPED_STRING
DEFLT_PROP : "font" | "fill"

output_stmt : "output" "{" output_option* "}"
output_option : _path_option
    | _size_option
    | /color/ "=" ESCAPED_STRING
    | /background/ "=" ESCAPED_STRING
    | _margin_option
    | border_spec

cover_stmt : "cover" "{" cover_option+ "}"
cover_option : _path_option
    | /fit/ "=" WORD # check the actual string in the Transformer
    | /crop/ "=" WORD
    | /align/ "=" WORD
    | _margin_option
    | border_spec

image_stmt : "image" ESCAPED_STRING? "{" image_option+ "}"
image_option : _path_option
    | _size_option
    | /mask/ "=" WORD
    | _position_option

text_stmt : "text" ESCAPED_STRING? "{" text_option+ "}"
text_option : /text/ "=" ESCAPED_STRING
    | _size_option
    | _position_option
    | /rotation/ "=" INTEGER
    | /fill/ "=" ESCAPED_STRING
    | /font/ "=" ESCAPED_STRING
    | stroke_spec

border_spec : "border" "{" border_option+ "}"
border_option : /color/ "=" ESCAPED_STRING
    | width_option

stroke_spec : "stroke" "{" stroke_option+ "}"
stroke_option : _color_option
    | /width/ "=" INTEGER

width_option : "width" "=" INTEGER
    | "width" "{" INTEGER "}"
    | "width" "{" one_side+ "}"
one_side : /[ltrb]/ "=" INTEGER

_path_option : /path/ "=" ESCAPED_STRING
_margin_option : /margin/ "=" INTEGER
_size_option : /size/ "=" (SIZE|INTEGER)
_position_option : /position/ "=" ESCAPED_STRING
_color_option : /color/ "=" ESCAPED_STRING

SIZE : /\d+x\d+/
INTEGER : /[-+]?\d+/
%import common.ESCAPED_STRING
%import common.SH_COMMENT
%import common.WS
%import common.WORD
%ignore SH_COMMENT
%ignore WS
