mupic_config_file : include_stmt? setting_stmt* default_stmt* _stmts

_stmts : statement*

?statement : output_stmt
    | image_stmt  | text_stmt
    | template_stmt | render_stmt

include_stmt : "include" ESCAPED_STRING

setting_stmt : "set" "zorder" CNAME -> zorder_stmt

default_stmt : "default" DEFLT_PROP STRING_VALUE
DEFLT_PROP : "font" | "fill"

output_stmt : "output" "{" output_setting+ "}"
OUTPUT_FIT : "cover" | "contain"
?output_setting : path_option
    | size_2d_option
    | color_option
    | "background" "=" STRING_VALUE -> background_option
    | "fit" "=" OUTPUT_FIT -> fit_option
    | margin_int_option
    | border_spec

image_stmt : "image" [(ESCAPED_STRING | CNAME) [ INTEGER]] "{" image_setting+ "}"
?image_setting : path_option
    | "size" "=" /max(square)?/ -> size_max
    | "size" "=" "scale" "," FLOAT -> scale_size
    | size_2d_option
    | "mask" "=" WORD -> mask_option
    | "fit" "=" "stretch" -> fit_stretch
    | "fit" "=" "contain" "," MINMAX -> fit_contain
    | "fit" "=" "fill" "," MINMAX -> fit_fill
    | position_option
    | border_spec
    | color_option
    | path_option
    | border_spec
    | margin_int_option

text_stmt : "text" [(ESCAPED_STRING | CNAME) [ INTEGER]] "{" text_setting+ "}"
?text_setting : "text" "=" ESCAPED_STRING -> text_option
    | "size" "=" INTEGER -> size_int_option
    | position_option
    | color_option
    | "rotation" "=" INTEGER -> rotation_int_option
    | "fill" "=" STRING_VALUE -> fill_option // This is a color
    | "font" "=" STRING_VALUE -> font_option
    | stroke_spec
    | "gap" "=" INTEGER -> gap_int_option
    | border_spec

template_stmt : "template" CNAME "(" parm_list ")" TBODY
parm_list : /[a-zA-Z]/ ("," /[a-zA-Z]/)*
TBODY.50 : /\{\{\{/ /.+?(?=}}})/s /\}\}\}/

render_stmt : "render" CNAME "(" render_list ")"
render_list : STRING_VALUE ("," STRING_VALUE)*

border_spec : "border" "{" border_setting+ "}"
    | "border" "=" (HEXCOLOR | ESCAPED_STRING | CNAME) ","  INTEGER-> simple_border
// Changing this to directly use color_option rule
// causes a reduce/reduce conflict with stroke_setting
?border_setting : "color" "=" (HEXCOLOR | ESCAPED_STRING | WORD) -> color_option
    | width_spec
    | "round" "=" INTEGER -> round_int_option

stroke_spec : "stroke" "{" stroke_setting+ "}"
?stroke_setting : color_option
    | "width" "=" INTEGER -> width_int_option

width_spec : "width" "=" INTEGER
    | "width" "{" INTEGER "}"
    | "width" "{" one_side+ "}"
one_side : /[ltrb]/ "=" INTEGER

path_option : "path" "=" STRING_VALUE
margin_int_option : "margin" "=" INTEGER
size_2d_option : "size" "=" SIZE
position_option : "position" "=" STRING_VALUE
color_option : "color" "=" (HEXCOLOR | ESCAPED_STRING | CNAME)

SIZE : /\d+(x\d+)?/
INTEGER : /[-+]?\d+/
BARE_STRING : /[^)( \t,\n"']+/
%import common.ESCAPED_STRING
%import common.WORD
%import common.CNAME
%import common.FLOAT

STRING_VALUE : ESCAPED_STRING | BARE_STRING
MINMAX.10 : /min\b|mid\b|max\b/i


// Priority is to make it tried before SH_COMMENT
HEXCOLOR.10 : /\#[a-fA-F0-9]+/

%import common.SH_COMMENT
%import common.WS
%ignore SH_COMMENT
%ignore WS
