start : simple_pos
    | attach_pos
    | overlay_pos

// --- SIMPLE
simple_pos : LR_POS "-" TB_POS [ "-" INTEGER ]
LR_POS : /left\b|center\b|right\b/i
TB_POS : /top\b|bottom\b|center\b/i

// --- ATTACH
attach_pos : "attach" "(" triple "," side "," pos_values ["," anchor_values] ["," offset] ")"

pos_values : (MINMAX | PERCENT) "," (MINMAX | PERCENT)
anchor_values : MINMAX "," MINMAX
side : PIECE
offset : INTEGER



// --- OVERLAY
overlay_pos : "overlay" "(" triple "," pos_values ["," anchor_values] ["," offset] ")"

// ---- COMMON STUFF

// alteration needed because of the higher priority of SUB_ELEMENT.
// If 'border' is given as the ELEMENT_NAME it will be parsed as
// a SUB_ELEMENT.
triple : (ELEMENT_NAME | SUB_ELEMENT) ["." SUB_ELEMENT] ["." PIECE]

// Unsigned only
INTEGER.10 : /\d+/

PERCENT.10 : INTEGER "%"
SUB_ELEMENT.10 : /full\b|margin\b|border\b|content\b/i
PIECE.10 : /left\b|right\b|top\b|bottom\b/i
ELEMENT_NAME : ESCAPED_STRING | REF_BARE_STRING

REF_BARE_STRING : /[^)( \t,\n"':\.;]+/

%import common.ESCAPED_STRING

MINMAX.10 : "min" | "mid" | "max"
REF_STRING_VALUE : ESCAPED_STRING | REF_BARE_STRING

%import common.WS
%ignore WS
