start : simple_pos
    | attach_pos
    | overlay_pos

// --- SIMPLE
simple_pos : LR_POS "-" TB_POS [ "-" INTEGER ]
LR_POS : /left\b|center\b|right\b/i
TB_POS : /top\b|bottom\b|center\b/i

// --- ATTACH
attach_pos : "attach" "(" triple "," side "," one_pos_value ["," MINMAX] ["," offset] ")"

anchor_values : MINMAX "," MINMAX
side : PIECE
offset : INTEGER

one_pos_value : MINMAX | POS_VALUE

// --- OVERLAY
overlay_pos : "overlay" "(" triple "," pos_values ["," anchor_values] ["," offset] ")"
pos_values : one_pos_value "," one_pos_value

// ---- COMMON STUFF

// alteration needed because of the higher priority of SUB_ELEMENT.
// If 'border' is given as the ELEMENT_NAME it will be parsed as
// a SUB_ELEMENT.
triple : (ELEMENT_NAME | SUB_ELEMENT) ["." SUB_ELEMENT] ["." PIECE]

INTEGER.5 : /\d+/

// A possibly signed integer followed by a unit
POS_VALUE.10 : /[+-]?\d+(%|px)?/

SUB_ELEMENT.10 : /full\b|margin\b|border\b|content\b/i
PIECE.10 : /left\b|right\b|top\b|bottom\b/i
ELEMENT_NAME : ESCAPED_STRING | REF_BARE_STRING

REF_BARE_STRING : /[^)( \t,\n"':\.;]+/

%import common.ESCAPED_STRING

MINMAX.10 : /min\b|mid\b|max\b/i
REF_STRING_VALUE : ESCAPED_STRING | REF_BARE_STRING

%import common.WS
%ignore WS
