start : simple_pos
    | attach_pos
    | overlay_pos

// --- SIMPLE
simple_pos : LR_POS "-" TB_POS [ "-" INTEGER ]
LR_POS : "left" | "right" | "center"
TB_POS : "top" | "bottom" | "center"

// --- ATTACH
attach_pos : WS* "attach" WS* "(" WS* ref_value WS* pos_values [ WS* anchor_values] [WS* offset ] WS* ")" WS*
ref_value : REF_STRING_VALUE ":" WORD [":" WORD]
one_pos_value : "," WS* (PERCENT | MINMAX)
pos_values : one_pos_value WS* one_pos_value
anchor_values : "," WS* MINMAX WS* "," WS* MINMAX
offset : "," WS* INTEGER

// --- OVERLAY
overlay_pos : WS* "overlay" WS* "(" WS* ref_value WS* pos_values [ WS* anchor_values] [WS* offset ] WS* ")" WS*

// ---- COMMON STUFF

// Unsigned only
INTEGER.10 : /\d+/

PERCENT.10 : INTEGER "%"

REF_BARE_STRING : /[^)( \t,\n"':]+/

%import common.WORD
%import common.ESCAPED_STRING

MINMAX.10 : "min" | "mid" | "max"
REF_STRING_VALUE : ESCAPED_STRING | REF_BARE_STRING

// Note we are not going to ignore whitespace.
%import common.WS
